# Generated by Django 5.1.7 on 2025-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gobelin', 'Gobelin'), ('Orc', 'Orc'), ('Ogre', 'Ogre'), ('Centaure', 'Centaure'), ('Dragon', 'Dragon')], max_length=50)),
                ('degats', models.IntegerField()),
                ('pv', models.IntegerField()),
            ],
        ),
    ]
