# Generated by Django 5.1.7 on 2025-03-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon'),
        ),
    ]
