# Generated by Django 5.1.7 on 2025-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_remove_character_classe_character_pv_character_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Nain', 'Nain'), ('Elfe', 'Elfe'), ('Humain', 'Humain')], max_length=50),
        ),
    ]
