# Generated by Django 5.1.7 on 2025-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='numColonne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='numLigne',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
