# Generated by Django 5.1.7 on 2025-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Hallebarde', 'Hallebarde'), ('Epée', 'Epee'), ('Arc', 'Arc'), ('Baton', 'Baton'), ('Dague', 'Dague'), ('Fléau', 'Fleau'), ('Epée longue', 'Epee Longue')], max_length=50),
        ),
    ]
